environment                   = "dev"
aws_region                    = "us-east-1"
vpc_cidr                      = "10.0.0.0/16"
availability_zones            = ["us-east-1a", "us-east-1b"]
enable_nat_gateway            = false
dynamodb_billing_mode         = "PAY_PER_REQUEST"
enable_point_in_time_recovery = false
cognito_mfa_configuration     = "OPTIONAL"
api_throttle_burst_limit      = 1000
api_throttle_rate_limit       = 2000
